[package]
name = "nvmc-demo"
version = "0.1.0"
authors = ["Christopher Hunt"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
embedded-storage = "0.1.0"
rtt-target = {version = "0.2.0", features = ["cortex-m"] }

[dependencies.embedded-hal]
version = "0.2.3"
features = ["unproven"]

[dependencies.nrf52840-hal]
features = ["rt"]
path = "../../nrf52840-hal"
optional = true

[features]
52840 = ["nrf52840-hal"]
