name: CI

on:
  push:
    branches: [ master, staging, trying ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: ${{ matrix.rust_version == 'nightly' }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust_version }}
        profile: minimal
        override: true
    - name: Install Arm targets
      run: >
        rustup target add
        thumbv6m-none-eabi
        thumbv7em-none-eabi
        thumbv7em-none-eabihf
        thumbv8m.main-none-eabi
    - name: Build Crates
      run: cargo test -p xtask
      env:
        RUSTFLAGS: ${{ matrix.rustflags }}

    strategy:
      matrix:
        rust_version: [beta, nightly]
        include:
          - rust_version: stable
            rustflags: --deny warnings

  hil:
    runs-on: ubuntu-latest
    # The secrets are not supplied for 'pull_request' events, so don't run for those.
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # everything
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: not needed
    - name: Push changes to CI repository
      run: |
        git checkout -b hil-run
        git remote add ci git@github.com:jonas-schievink/nrf-hal-ci.git
        git push -f -u ci hil-run
        sleep 5
    - name: Trigger and wait for HIL workflow
      uses: jonas-schievink/workflow-proxy@v1
      with:
        workflow: HIL
        ref: hil-run
        repo: jonas-schievink/nrf-hal-ci
        token: ${{ secrets.PRIVATE_CI_PERSONAL_ACCESS_TOKEN }}
        repost-logs: true

  ci:
    if: ${{ success() }}
    # all new jobs must be added to this list
    needs: [build, hil]
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
